apiVersion: apps/v1
kind: Deployment
metadata:
  name: qik-whatsapp
  labels:
    app: qik-whatsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qik-whatsapp
  template:
    metadata:
      labels:
        app: qik-whatsapp
    spec:
      containers:
        - name: whatsaap-qik
          # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
          image: 593881202230.dkr.ecr.us-east-1.amazonaws.com/whatsaap-qik:latest
          ports:
            - containerPort: 3000
